### ISSUE TITLE
Unable to find token seed!

### ISSUE THREAD

**Issue by UmarAbdullahi** [jaspreetsidhu3/text_to_mp3-audiobook#1]
**Hi, 
I've been running into this error:**

Traceback (most recent call last):
  File "jelly.py", line 37, in <module>
    gtts_obj.save(filename + ".mp3")
  File "C:\Users\Umar\AppData\Local\Programs\Python\Python38\lib\site-packages\gtts\tts.py", line 295, in save
    self.write_to_fp(f)
  File "C:\Users\Umar\AppData\Local\Programs\Python\Python38\lib\site-packages\gtts\tts.py", line 251, in write_to_fp
    prepared_requests = self._prepare_requests()
  File "C:\Users\Umar\AppData\Local\Programs\Python\Python38\lib\site-packages\gtts\tts.py", line 194, in _prepare_requests
    part_tk = self.token.calculate_token(part)
  File "C:\Users\Umar\AppData\Local\Programs\Python\Python38\lib\site-packages\gtts_token\gtts_token.py", line 28, in calculate_token
    seed = self._get_token_key()
  File "C:\Users\Umar\AppData\Local\Programs\Python\Python38\lib\site-packages\gtts_token\gtts_token.py", line 58, in _get_token_key
    raise ValueError(
ValueError: Unable to find token seed! Did https://translate.google.com change?

**Any idea what to do?**

**Comment by jaspreetsidhu3** [comment]
Hi UmarAbdullahi, 
I found that this issue is also present at gTTS repository (which our project uses) https://github.com/pndurette/gTTS/issues/232. So maybe this issue cannot be resolved till further update from gTTS or you may follow given link for more update.

**Comment by jaspreetsidhu3** [comment]
Hi UmarAbdullahi,
Sorry for the inconvenience. Now I have updated the source code you may check.
